GET http://localhost:8080/dsTivi
####
GET http://localhost:8080/Cuahang
###
GET http://localhost:8080/dsHocsinh
### Test Img
GET  http://localhost:8080/IPHONE_1.png
###
GET  http://localhost:8080/dsNguoidung
###
POST http://localhost:8080/ThemNguoidung
Content-Type: application/json

{
    "Ten": "Nguyễn Anh Tuấn",
    "Ma_so": "QL_3",
    "Ten_Dang_nhap": "natuan",
    "Mat_khau": "tuan010542",
    "Nhom_Nguoi_dung": {
        "Ten": "Nhân viên Quản trị",
        "Ma_so": "QUAN_TRI"
    }
}
###
POST http://localhost:8080/SuaNguoidung
Content-Type: application/json

{
    "Ten": "Nguyễn Anh Tài",
    "Ma_so": "QL_3",
    "Ten_Dang_nhap": "natai",
    "Mat_khau": "natai"
    
}
###
POST http://localhost:8080/XoaNguoidung
Content-Type: application/json

{
    "Ma_so": "QL_99"
}